title: "Web Günlüğü"
description: "Bilim, teknoloji, yazılım, kodlama ile ilgili yazıların bulunduğu başka bir blog"
email: zfrznt@gmail.com
timezone: Europe/Istanbul
baseurl: "/"
permalink: ":year/:month/:slug.html"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: Sal
paginate: 5
disqus: 'webgunlugu-1'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-105364251-1

# Authors
authors:
  sal:
    name: Zafer
    display_name: Zafer
    avatar: 'assets/images/sal.png'
    email: zfrznt@gmail.com
    web: https://www.zaferzent.com
    twitter: https://twitter.com/zaferzent
    description: "Author of Affiliates, a template available for WordPress, HTML, Ghost and Jekyll. You are currently previewing Jekyll template demo."
  john:
    name: John
    display_name: John
    avatar: 'assets/images/john.png'
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net/category/jekyll-themes/
    twitter: https://twitter.com/wowthemesnet
    description: "This is the author box. Write a short description of the author here. You are currently previewing Affiliates theme demo, a Jekyll template compatible with Github pages."

# Social
social:
  instagram: https://www.instagram.com/
  facebook: https://www.facebook.com/
  twitter: https://twitter.com/

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
